repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/PyCQA/bandit
  rev: 1.9.0
  hooks:
  - id: bandit
    args: [ '-c', 'bandit.yaml', '-r', '.' ]
    exclude: ^tests/

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.14.5
  hooks:
  - id: ruff
    args: [ '--config', 'pyproject.toml', 'check', '.' ]
    language_version: python3

# Exclude common generated/static paths to avoid noisy checks
exclude: |
  (?x)
  (^|/)(\.venv|venv|env|\.eggs|\.git|node_modules|staticfiles|static|migrations)(/|$)
